#!/bin/bash

#/************************************************************************************
#***
#***	Copyright 2008 Hon Hai Precision Ind. Co. Ltd., All Rights Reserved.
#***
#***	No portions of this material shall be reproduced in any form without
#***	the written permission of Hon Hai Precision Ind. Co. Ltd.
#***
#***	All information contained in this document is Hon Hai Precision Ind.  
#***	Co. Ltd. company private, proprietary, and trade secret property and 
#***	are protected by international intellectual property laws and treaties.
#***
#***
#***	File Author: Dell, Mon Apr 21 09:14:47 CST 2008
#***
#************************************************************************************/

export LC_ALL=C

function applet_orignal_list()
{
	grep =y busybox.config | sed -e "s/=y//" -e "s/CONFIG_//" | tr A-Z a-z
}

function applet_sorted_list()
{
	grep =y busybox.config | sed -e "s/=y//" -e "s/CONFIG_//" | tr A-Z a-z | sort
}


function applet_source()
{
	sorted_applets=`applet_sorted_list`

	for f in $sorted_applets ; do
		echo "${f}_main.cpp"
	done
}

function applet_table()
{
	sorted_applets=`applet_sorted_list`

	echo
	echo "/* Warning: "
	echo " * Don't edit this table manually. !!! "
	echo " *"
	echo " */"

	echo	

	for f in $sorted_applets ; do
		echo "extern int ${f}_main(int agrc, char **argv);"
	done
	echo 

	echo "static applet_t applet_table[] = {"
	for f in $sorted_applets ; do
		echo -e "\t{ (char *)\"$f\", ${f}_main },"
	done
	echo "};"
	echo

	orignal_applets=`applet_orignal_list`
	echo "static applet_t help_table[] = {"
	for f in $orignal_applets ; do
		echo -e "\t{ (char *)\"$f\", ${f}_main },"
	done
	echo "};"
	echo
}

function applet_links()
{
	local DIR=$1
	sorted_applets=`applet_sorted_list`

	cd ${DIR}
	for f in $sorted_applets ; do
		ln -sf busybox $f
	done
	cd ${OLDPWD}
}


function help()
{
	echo "Usage: $1 [options]";
	echo "options:"
	echo "    --help      Display this help."
	echo "    --source    Source list."
	echo "    --table     Function table."
}

function main()
{
	case "$1" in
	--help)
		help "$0";;
	--source)
		applet_source;;
	--table)
		applet_table;;
	--links)
		applet_links "$2" ;;
	*)
		help "$0";;
	esac

}

main "$@"
